# Generated by Django 2.2.9 on 2020-02-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.IntegerField(choices=[(0, '非公開'), (1, '公開')], default=0),
        ),
    ]
