# Generated by Django 2.2.9 on 2020-02-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Can access articles for pro', verbose_name='active'),
        ),
    ]
